name: curl
on:
  push:
  schedule:
    - cron: '0/20 * * * *'
  workflow_dispatch:
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: curl
      run: bash ./curl.sh
