name: data
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
jobs:
  get:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: curl
      uses: wei/curl@master
      with:
        args: -X GET -H "X-LC-Id:${{ secrets.LEANCLOUD_ID }}" -H "X-LC-Key:${{ secrets.LEANCLOUD_KEY }}" -G --data-urlencode "limit=5" --data-urlencode "keys=url,ov,uv,like" -o counter.json ${{ secrets.LEANCLOUD_API }}/1.1/classes/Counter 
    - name: commit
      run: |
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m "Update"
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
